devices:
  xxxxxxxxxxxxx:
    connections:
      cli:
        ip: 250.250.250.250
        protocol: ssh
    credentials:
      default:
        password: xxxxxxxxx
        username: yyyyyyyyy
      enable:
        password: xxxxxxxxx
    os: ios
    type: ios
