devices:
  0700-I11-SWITC-002:
    connections:
      cli:
        ip: 10.236.223.30
        protocol: ssh
    credentials:
      default:
        password: Yemi1985%
        username: oshuno
      enable:
        password: Yemi1985%
    os: ios
    type: ios
  ADNOCSG-AAT-CAMAGG01:
    connections:
      cli:
        ip: 10.236.107.10
        protocol: ssh
    credentials:
      default:
        password: Yemi1985%
        username: oshuno
      enable:
        password: Yemi1985%
    os: iosxe
    type: iosxe
  AHG-AAT-CSPL_01:
    connections:
      cli:
        ip: 10.236.7.254
        protocol: ssh
    credentials:
      default:
        password: Yemi1985%
        username: oshuno
      enable:
        password: Yemi1985%
    os: nxos
    type: nxos
  AHG-AAT-CSPL_02:
    connections:
      cli:
        ip: 10.236.7.249
        protocol: ssh
    credentials:
      default:
        password: Yemi1985%
        username: oshuno
      enable:
        password: Yemi1985%
    os: nxos
    type: nxos
  AHG-AAT-SFLEAF01:
    connections:
      cli:
        ip: 10.236.7.252
        protocol: ssh
    credentials:
      default:
        password: Yemi1985%
        username: oshuno
      enable:
        password: Yemi1985%
    os: nxos
    type: nxos